Skip to content
 
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 @pkofod Sign out
2
4 5 JuliaCI/Appveyor.jl
 Code  Issues 1  Pull requests 1  Projects 0  Wiki  Insights
Julia Appveyor script
 31 commits
 3 branches
 0 releases
 3 contributors
 PowerShell 89.5%	 Julia 10.5%
 @simonbyrne
simonbyrne Merge pull request #9 from JuliaCI/sb/norelease  …
Latest commit 2360762  a day ago
bin	remove 'release', add 'nightly' and 'X.Y.Z' support	a day ago
src	Add code for coverage	3 days ago
test	try it out	a month ago
.codecov.yml	Appveyor.jl generated files.	a month ago
.gitignore	Appveyor.jl generated files.	a month ago
.travis.yml	Appveyor.jl generated files.	a month ago
LICENSE.md	Appveyor.jl generated files.	a month ago
README.md	remove 'release', add 'nightly' and 'X.Y.Z' support	a day ago
REQUIRE	Appveyor.jl generated files.	a month ago
appveyor.yml	remove 'release', add 'nightly' and 'X.Y.Z' support	a day ago
 README.md
Appveyor.jl
Build status codecov.io

This contains a "universal" Appveyor script for Julia repositories, making it easier to set up matrix builds and keep URLs up-to-date.

Usage
Replace your appveyor.yml file with the following:

environment:
  matrix:
  - julia_version: 0.7
  - julia_version: 1
  - julia_version: nightly

platform:
  - x86 # 32-bit
  - x64 # 64-bit

# # Uncomment the following lines to allow failures on nightly julia
# # (tests will run but not make your overall status red)
# matrix:
#   allow_failures:
#   - julia_version: latest

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"

# # Uncomment to support code coverage upload. Should only be enabled for packages
# # which would have coverage gaps without running on Windows
# on_success:
#   - echo "%JL_CODECOV_SCRIPT%"
#   - C:\julia\bin\julia -e "%JL_CODECOV_SCRIPT%"
